// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package note

import (
	"NTNU_APP_2023_Final_Backend/api/note"
)

type ControllerV1 struct{}

func NewV1() note.INoteV1 {
	return &ControllerV1{}
}
