// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NTNU_APP_2023_Final_Backend/internal/dao/internal"
)

// internalCurriculumsDao is internal type for wrapping internal DAO implements.
type internalCurriculumsDao = *internal.CurriculumsDao

// curriculumsDao is the data access object for table curriculums.
// You can define custom methods on it to extend its functionality as you wish.
type curriculumsDao struct {
	internalCurriculumsDao
}

var (
	// Curriculums is globally public accessible object for table curriculums operations.
	Curriculums = curriculumsDao{
		internal.NewCurriculumsDao(),
	}
)

// Fill with you ideas below.
