// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"NTNU_APP_2023_Final_Backend/internal/dao/internal"
)

// internalNotesDao is internal type for wrapping internal DAO implements.
type internalNotesDao = *internal.NotesDao

// notesDao is the data access object for table notes.
// You can define custom methods on it to extend its functionality as you wish.
type notesDao struct {
	internalNotesDao
}

var (
	// Notes is globally public accessible object for table notes operations.
	Notes = notesDao{
		internal.NewNotesDao(),
	}
)

// Fill with you ideas below.
